services:
  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elastic_search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g # Limitar la memoria de la JVM
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8080
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic_search_network
    volumes:
      - elastic_search_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic_search:9200
    ports:
      - 5601:5601
    networks:
      - elastic_search_network

  elasticvue:
      image: cars10/elasticvue
      ports:
        - "8080:8080"
      depends_on:
        - elastic_search

volumes:
  elastic_search_data:
networks:
  elastic_search_network:
    driver: bridge